---
title: "Day 6"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages}
library(tidyverse)
library(here)
```

```{r read1}
read_pop <- function(fn){
  read_file(here("Input", fn)) %>%
    str_split(",", simplify = TRUE) %>%
    as.vector() %>%
    as.integer()
}

test_initpop <-  read_pop("test_06.txt")
input_initpop <- read_pop("input_06.txt")
```

# Part 1
```{r}
gen_pop_next <- function(x){
  n_new <- x %>% filter(timer==0) %>% pull(n)
  
  newx <- x %>% mutate(timer=if_else(timer>0, timer-1, 6)) %>%
    add_row(timer=8, n=n_new)
  
  newx %>% count(timer, wt=n)
}

gen_pop <- function(initpop, days){
  x <- table(initpop) %>% as_tibble() %>% 
    rename(timer=initpop) %>%
    mutate(timer=as.integer(timer))
  
  for (i in 1:days){
    x <- gen_pop_next(x)
  }
  npop <- x %>% pull(n) %>% sum()
  return(list(pop=x, npop=npop))
}

test18 <- gen_pop(test_initpop, 18)
test80 <- gen_pop(test_initpop, 80)
test18$npop
test80$npop

inp80 <- gen_pop(input_initpop, 80)
inp80$npop
```

# Part 2
```{r}
test256 <- gen_pop(test_initpop, 256)
test256$npop

inp256 <- gen_pop(input_initpop, 256)
formatC(inp256$npop, digits=13)
```

