---
title: "Day 3"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages}
library(tidyverse)
library(here)
```

```{r read1}
input <- read_table(here("Input", "input_03.txt"), 
                     col_names = c("value"))
input
test <- read_table(here("Input", "test_03.txt"), 
                     col_names = c("value"))
test
```

# Part 1
```{r part1}
read_diag_report <- function(report){
  ndig <- report %>% summarise(ndig=max(str_length(value))) %>% pull(ndig)
  
  meandigits <- report %>%
    separate(value, into=str_c("X", 1:ndig), sep=1:(ndig-1), convert=TRUE) %>%
    summarise(
      across(starts_with("X"), mean)
    )
  
  gamma_value <- meandigits %>%
    mutate(
      across(starts_with("X"), round),
      across(starts_with("X"), as.character)
      ) %>%
    unite("gamma", starts_with("X"), sep="") %>%
    mutate(
      gamma=strtoi(gamma, base=2)
    ) %>%
    pull(gamma)
  
  epsilon_value <- meandigits %>%
    mutate(
      across(starts_with("X"), round),
      across(starts_with("X"), ~1-.x),
      across(starts_with("X"), as.character)
      ) %>%
    unite("epsilon", starts_with("X"), sep="") %>%
    mutate(
      epsilon=strtoi(epsilon, base=2)
    ) %>%
    pull(epsilon)
  
  tibble(gamma=gamma_value, epsilon=epsilon_value) %>%
    mutate(ans=gamma*epsilon)
} 

read_diag_report(test)
read_diag_report(input)

```

# Part 2

```{r part2}

filter_i <- function(inp, i, type=c("oxy", "co2")){
  extdig <- inp %>%
    mutate(inpi=str_sub(value, i, i))
  
  digtab <- extdig %>% count(inpi)
  
  if (nrow(digtab)==2){
    n0 <- digtab %>% filter(inpi=="0") %>% pull(n)
    n1 <- digtab %>% filter(inpi=="1") %>% pull(n)
    if (n0 > n1){
      comp <- "mostly0"
    } else if (n1 > n0){
      comp <- "mostly1"
    } else{
      comp <- "tie"
    }
  } else {
    if (digtab$inpi=="0"){
      comp <- "mostly0"
    } else{
      comp <- "mostly1"
    }
  }
  
  if (type=="oxy"){
    if (comp %in% c("mostly1", "tie")){
      sel <- "1"
    } else{
      sel <- "0"
    }
  } else if (type=="co2"){
    if (nrow(digtab)==1){
      sel <- digtab$inpi
    } else if (comp %in% c("mostly1", "tie")){
      sel <- "0"
    } else{
      sel <- "1"
    }
    
  }
  
  extdig %>%
    filter(inpi==sel) %>%
    select(-inpi)
}

rating <- function(report){
  ndig <- report %>% summarise(ndig=max(str_length(value))) %>% pull(ndig)
  
  tmpreport_oxy <- report
  tmpreport_co2 <- report
  
  for (i in 1:ndig){
    tmpreport_oxy <- filter_i(tmpreport_oxy, i, "oxy")
    tmpreport_co2 <- filter_i(tmpreport_co2, i, "co2")
  }
  
  tibble(oxy=strtoi(tmpreport_oxy$value, base=2),
         co2=strtoi(tmpreport_co2$value, base=2)) %>%
    mutate(ans=oxy*co2)
  
}

rating(test)
rating(input)
```

